---
# Homebrew

- homebrew: update_homebrew=yes
  name: Make sure we're using the latest Homebrew

- homebrew: upgrade_all=yes
  name: Upgrade any already-installed formulae

- homebrew_tap: tap={{ item }}
  name: Add taps
  with_items: '{{ homebrew.taps }}'

- homebrew: name='{{ homebrew.packages }}'
  name: Install packages
